### ISSUE TITLE
好像没啥用唉

### ISSUE THREAD

**Issue by icespite** [Ice-Hazymoon/163_daka#3]
测了几天感觉没有效果ε=(´ο｀*)))唉

**Comment by Ice-Hazymoon** [comment]
可我天天都有效果( ｰ̀дｰ́ )

**Comment by icespite** [comment]
![image](https://user-images.githubusercontent.com/50160905/77511997-19d4de80-6ead-11ea-9d0b-ee23a305ad31.png)
是这个亚子吗

**Comment by Ice-Hazymoon** [comment]
是的，然后第二天看累计听歌数量

**Comment by MualaniMarine** [comment]
不知道这个数据是第二天何时刷新 ，昨天下午install完试了，凌晨的时候和刚刚看了眼，没变化。正打算改一下time再试试

**Comment by icespite** [comment]
> 不知道这个数据是第二天何时刷新 ，昨天下午install完试了，凌晨的时候和刚刚看了眼，没变化。正打算改一下time再试试

有效果了吗

**Comment by MualaniMarine** [comment]
应该是我自己的问题了，我找歌单听也没涨，我开了个小号再试试，如果仍无效果我再回报
